### ISSUE TITLE
Reproducing notebook example

### ISSUE THREAD

**Issue by staceyalberts** [kmlgould/GMM-quiescent#2]
Hi!

I am attempting to reproduce the example in your notebook using the data file literature_mqg_zout.fits.  I am not getting the right p(q) values, they are far lower than they should be.  In your example you reference file colours_model-v4.0.pkl, however, the file on github is colours_model-vf.0.pkl.  What is the difference between these files and the different "groupX_t" color models?

Thanks!
Stacey

**Comment by kmlgould** [comment]
Hi Stacey,

Thanks for getting in touch! 

I think what happened is that somewhere I forgot to change the model and associated quiescent group. I’ll explain using the attached diagram. 

When I made the Gaussian Mixture Model, I fit 5 gaussians to the NUV-U, U-V, V-J colour space of the reference sample (massive galaxies at 2<z<3 selected from the COSMOS2020 catalog, described in detail in the paper). 

This is shown as a cartoon in the attached diagram. By eye, I chose which one should be the “quiescent” group (because its basically UVJ area with more info), and then this group number is the group used to decide the probability of quiescence. 

For the v4 model, that was group 3 - but in the vf model, its actually group4 (which should be “zscore_t.T[3]”). 

Obviously, I got mixed up when updating the GitHub and updated the model but not the code - so thanks for catching that! 

This should be updated now. Please let me know if you still get different p(q) values than me! 

Cheers,

Kate 
[GMM_Explained.pdf](https://github.com/kmlgould/GMM-quiescent/files/12803455/GMM_Explained.pdf)

**Comment by staceyalberts** [comment]
Hi Kate,

I can reproduce your results now, thanks for your quick fix!

Cheers,
Stacey
